-- Creación de secuencias (MySQL no soporta secuencias, se usa AUTO_INCREMENT)
-- Usuarios
CREATE TABLE USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(64) NOT NULL
);

-- Procedimiento para registrar usuarios
DELIMITER $$
CREATE PROCEDURE REGISTRAR_USUARIO (
    IN P_NOMBRE VARCHAR(50),
    IN P_APELLIDO VARCHAR(50),
    IN P_CORREO VARCHAR(100),
    IN P_CONTRASENA VARCHAR(64)
)
BEGIN
    INSERT INTO USUARIOS (NOMBRE, APELLIDO, CORREO, CONTRASENA)
    VALUES (P_NOMBRE, P_APELLIDO, P_CORREO, P_CONTRASENA);
END $$
DELIMITER ;

-- Colaboradores
CREATE TABLE COLABORADORES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(64) NOT NULL
);

-- Insertar datos iniciales
INSERT INTO COLABORADORES (NOMBRE, APELLIDO, CORREO, CONTRASENA)
VALUES ('Juan', 'Perez', 'Juan@gmail.com', '1234');

-- Remitente
CREATE TABLE REMITENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CEDULA VARCHAR(20) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL
);

-- Destinatario
CREATE TABLE DESTINATARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CEDULA VARCHAR(20) NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    HORA_RETIRO VARCHAR(10) NOT NULL
);

-- Paquete
CREATE TABLE PAQUETE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(500) NOT NULL,
    ESPECIFICACIONES VARCHAR(500) NOT NULL,
    DIRECCION_RETIRO VARCHAR(200) NOT NULL,
    DIRECCION_ENTREGA VARCHAR(200) NOT NULL,
    REMITENTE_ID INT NOT NULL,
    DESTINATARIO_ID INT NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    CONSTRAINT FK_REMITENTE FOREIGN KEY (REMITENTE_ID) REFERENCES REMITENTE(ID),
    CONSTRAINT FK_DESTINATARIO FOREIGN KEY (DESTINATARIO_ID) REFERENCES DESTINATARIO(ID)
);

-- Procedimiento para insertar remitente
DELIMITER $$
CREATE PROCEDURE INSERTAR_REMITENTE (
    IN P_NOMBRE VARCHAR(100),
    IN P_CEDULA VARCHAR(20),
    IN P_CORREO_ELECTRONICO VARCHAR(100),
    IN P_TELEFONO VARCHAR(15),
    OUT P_ID INT
)
BEGIN
    INSERT INTO REMITENTE (NOMBRE, CEDULA, CORREO_ELECTRONICO, TELEFONO)
    VALUES (P_NOMBRE, P_CEDULA, P_CORREO_ELECTRONICO, P_TELEFONO);
    SET P_ID = LAST_INSERT_ID();
END $$
DELIMITER ;

-- Procedimiento para insertar destinatario
DELIMITER $$
CREATE PROCEDURE INSERTAR_DESTINATARIO (
    IN P_NOMBRE VARCHAR(100),
    IN P_CEDULA VARCHAR(20),
    IN P_CORREO_ELECTRONICO VARCHAR(100),
    IN P_TELEFONO VARCHAR(15),
    IN P_HORA_RETIRO VARCHAR(10),
    OUT P_ID INT
)
BEGIN
    INSERT INTO DESTINATARIO (NOMBRE, CEDULA, CORREO_ELECTRONICO, TELEFONO, HORA_RETIRO)
    VALUES (P_NOMBRE, P_CEDULA, P_CORREO_ELECTRONICO, P_TELEFONO, P_HORA_RETIRO);
    SET P_ID = LAST_INSERT_ID();
END $$
DELIMITER ;

-- Procedimiento para insertar paquete
DELIMITER $$
CREATE PROCEDURE INSERTAR_PAQUETE (
    IN P_DESCRIPCION VARCHAR(500),
    IN P_ESPECIFICACIONES VARCHAR(500),
    IN P_DIRECCION_RETIRO VARCHAR(200),
    IN P_DIRECCION_ENTREGA VARCHAR(200),
    IN P_REMITENTE_ID INT,
    IN P_DESTINATARIO_ID INT,
    OUT P_ID INT
)
BEGIN
    INSERT INTO PAQUETE (DESCRIPCION, ESPECIFICACIONES, DIRECCION_RETIRO, DIRECCION_ENTREGA, REMITENTE_ID, DESTINATARIO_ID, fecha)
    VALUES (P_DESCRIPCION, P_ESPECIFICACIONES, P_DIRECCION_RETIRO, P_DIRECCION_ENTREGA, P_REMITENTE_ID, P_DESTINATARIO_ID, CURRENT_DATE);
    SET P_ID = LAST_INSERT_ID();
END $$
DELIMITER ;

-- Consultas de datos
SELECT * FROM REMITENTE;
SELECT * FROM DESTINATARIO;
SELECT * FROM PAQUETE;
SELECT * FROM USUARIOS;
SELECT * FROM COLABORADORES;

-- Eliminar tablas y procedimientos (MySQL no soporta procedimientos con DDL dinámico)
-- Las tablas deben ser eliminadas manualmente si es necesario.
